// vmnet lifecycle bridge: the three vmnet_network_configuration_* calls that
// CREATE a configuration or network return an opaque vmnet ref through a
// vmnet_return_t status out-parameter. That C-function shape (opaque-ref return
// plus a scalar out-parameter) is not yet generated by the idiomatic binding's
// C-function emitter, so these three are bound directly here. Every other vmnet
// call in the vmnet-direct engine uses the generated idiomatic functions; the
// opaque refs cross between the two as objc.ID (for the raw calls) and obj.Object
// (for the idiomatic ones, via obj.Wrap).
//go:build darwin

package network

import (
	"sync"

	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	vmnet "github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/framework/vmnet"
)

var (
	vmnetBridgeOnce      sync.Once
	vmnetBridgeLib       uintptr
	fnVmnetConfigCreate  func(vmnet.Operating_modes_t, *vmnet.Vmnet_return_t) objc.ID
	fnVmnetSetIpv4Subnet func(objc.ID, string, string) vmnet.Vmnet_return_t
	fnVmnetNetworkCreate func(objc.ID, *vmnet.Vmnet_return_t) objc.ID
)

func vmnetBridgeInit() {
	vmnetBridgeOnce.Do(func() {
		vmnetBridgeLib, _ = purego.Dlopen(
			"/System/Library/Frameworks/vmnet.framework/vmnet",
			purego.RTLD_GLOBAL|purego.RTLD_LAZY,
		)
		purego.RegisterLibFunc(&fnVmnetConfigCreate, vmnetBridgeLib, "vmnet_network_configuration_create")
		purego.RegisterLibFunc(&fnVmnetSetIpv4Subnet, vmnetBridgeLib, "vmnet_network_configuration_set_ipv4_subnet")
		purego.RegisterLibFunc(&fnVmnetNetworkCreate, vmnetBridgeLib, "vmnet_network_create")
	})
}

// vmnetNetworkConfigurationCreate wraps vmnet_network_configuration_create,
// returning the new configuration ref (0 on failure) and the vmnet status.
func vmnetNetworkConfigurationCreate(mode vmnet.Operating_modes_t) (objc.ID, vmnet.Vmnet_return_t) {
	vmnetBridgeInit()
	var status vmnet.Vmnet_return_t
	return fnVmnetConfigCreate(mode, &status), status
}

// vmnetNetworkConfigurationSetIpv4Subnet wraps
// vmnet_network_configuration_set_ipv4_subnet.
func vmnetNetworkConfigurationSetIpv4Subnet(config objc.ID, startAddress, endAddress string) vmnet.Vmnet_return_t {
	vmnetBridgeInit()
	return fnVmnetSetIpv4Subnet(config, startAddress, endAddress)
}

// vmnetNetworkCreate wraps vmnet_network_create, returning the new network ref
// (0 on failure) and the vmnet status.
func vmnetNetworkCreate(config objc.ID) (objc.ID, vmnet.Vmnet_return_t) {
	vmnetBridgeInit()
	var status vmnet.Vmnet_return_t
	return fnVmnetNetworkCreate(config, &status), status
}
